a=input('Digite algo:')
print('O tipo primitivo desse valor é', type (a))
print('So tem espaços?', a.isspace())
print('É numérico?', a.isnumeric())
print('É alfabeto?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está tudo em maiúsuculo?',a.isupper())
print('Está tudo em minúsculo?', a.islower())
print('Pode ser impresso?', a.isprintable())
print('Está capitalizado?', a.istitle())
